---
- name: Inspeccionar control CIS con Goss
  hosts: "{{ target_ip | default('localhost') }}" 
  become: true
  tasks:
    - name: Copiar el binario de Goss al servidor remoto
      ansible.builtin.copy:
        src: goss/goss
        dest: /usr/local/bin/goss
        mode: '0755'

    - name: Copiar el archivo de configuración de Goss
      ansible.builtin.copy:
        content: |
          file:
            /etc/ssh/sshd_config:
              exists: true
              mode: "0600"
              contents:
                - "PermitRootLogin no"
        dest: /tmp/goss.yaml
        mode: '0644'

    - name: Ejecutar validación de Goss
      ansible.builtin.command: /usr/local/bin/goss --gossfile /tmp/goss.yaml validate -f documentation
      register: goss_result
      failed_when: false  # No marque la tarea como fallida automáticamente
      changed_when: false

    - name: Mostrar resultados de la validación
      ansible.builtin.debug:
        msg: |
          Resultados de la validación de Goss:
          {{ goss_result.stdout }}

    - name: Reportar errores si los hay
      ansible.builtin.fail:
        msg: |
          Fallos detectados en la validación de Goss:
          {{ goss_result.stdout }}
      when: goss_result.rc != 0  # Marca el playbook como fallido si hay errores en Goss


