---
- name: Aplicar el rol CIS Security
  hosts: "{{ target_ip | default('localhost') }}"  # Proporciona 'localhost' como valor por defecto
  become: true
  gather_facts: true

  roles:
    - role: cis_security






