- name: Tarea que utiliza el entorno seleccionado
  hosts: "{{ target_environment }}"
  gather_facts: no
  tasks:
    - name: Imprimir mensaje de entorno
      debug:
        msg: "Ejecutando en el entorno: {{ target_environment }}"

    - name: Prueba de ping al host seleccionado
      ping:
      register: ping_result

    - name: Mostrar resultado del ping
      debug:
        msg: "Resultado del ping: {{ ping_result }}"
