---
- name: Tarea que utiliza el entorno seleccionado
  hosts: "{{ target_ip | default('localhost') }}"  # Proporciona 'localhost' como valor por defecto
  gather_facts: false
  tasks:

    - name: Obtener la fecha del host remoto
      ansible.builtin.command: date
      register: date_result  # Captura el resultado del comando date
      changed_when: false  # Indica que esta tarea nunca realiza cambios

    - name: Mostrar la fecha obtenida
      ansible.builtin.debug:
        var: date_result.stdout  # Muestra solo la salida estándar (fecha)

