- name: Tarea que utiliza el entorno seleccionado
  hosts: pruebas
  gather_facts: no
  tasks:

    - name: Realizar ping al host
      ping:

    - name: Mostrar el resultado del ping
      debug:
        var: ansible_facts.ping
