- name: Tarea que utiliza el entorno seleccionado
  hosts: pruebas
  gather_facts: no
  tasks:

    - name: Realizar ping al host
      ping:
      register: ping_result  # Captura el resultado del ping

    - name: Mostrar el resultado del ping
      debug:
        var: ping_result  # Muestra el contenido de la variable ping_result
