- name: Tarea que utiliza el entorno seleccionado
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Prueba de ping al host seleccionado
      ping:
      register: ping_result

    - name: Mostrar resultado del ping
      debug:
        msg: "Resultado del ping: {{ ping_result }}"
