--- 

# Tarea 2.1.1 - Asegurar que la sincronización de tiempo está en uso (Automático)
- name: NOTSCORED | 2.1.1 | PATCH | Ensure time synchronization is in use - service
    install {{ rhel8_cis_time_synchronization }}
  ansible.builtin.package:
    name: '{{ rhel8_cis_time_synchronization }}'
    state: present
  when:
    - rhel8_cis_rule_2_1_1
  tags:
    - level1
    - patch
    - ntp
    - rule_2.1.1

- name: 'NOTSCORED | 2.1.1 | PATCH | Ensure time synchronization is in use - service
    start '
  ansible.builtin.service:
    name: '{{ rhel8_cis_time_synchronization }}d'
    state: started
    enabled: true
  when:
    - rhel8_cis_rule_2_1_1
  tags:
    - level1
    - patch
    - ntp
    - rule_2.2.1

# Tarea 2.1.3 - Asegurar que chrony está configurado (Automático)
- name: SCORED | 2.1.3 | PATCH | Ensure chrony is configured
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - rhel8_cis_rule_2_1_3
  tags:
    - level1
    - patch
    - ntp
    - rule_2.1.3
