---
### Verificación Paquete xinetd
# Tarea 2.1.4 - Solicitar al usuario si xinetd es requerido
- name: Solicitar al usuario si xinetd es requerido
  pause:
    prompt: "¿El paquete xinetd está instalado? xinetd es un super servidor que gestiona otros servicios en la red. ¿Este sistema utiliza xinetd? (yes/no)"
  register: is_xinetd_required
  when: "'xinetd' in ansible_facts.packages"
# Tarea 2.1.4 - Asegurar que xinetd no está instalado (Automático)
- name: SCORED | 2.1.4 | PATCH | Ensure xinetd is not installed
  package:
    name: xinetd
    state: absent
  when:
    - "'xinetd' in ansible_facts.packages"
    - is_xinetd_required == "no"
    - rhel8_cis_rule_2_1_4
  tags:
    - level1
    - patch
    - xinetd
    - scored
    - rule_2.1.4


### Verificación Paquete xorg-x11-server-*
# Tarea 2.1.5 - Solicitar al usuario si x11 es requerido
- name: Solicitar al usuario si x11 es requerido
  pause:
    prompt: "¿El paquete x11 está instalado? X11 proporciona un sistema gráfico para las aplicaciones. ¿Este sistema utiliza x11? (yes/no)"
  register: is_x11_required
  when: ansible_facts.packages | select('match', '^xorg-x11-server-') | list | length > 0
# Tarea 2.1.5 - Asegurar X Window System (X11 Server Components) no esté instalado (Automático)
### DESHABILITADO - se utiliza para login a perfil web de internet
- name: SCORED | 2.1.5 | PATCH | Ensure X Window System is not installed
  package:
    name: xorg-x11-server-*
    state: absent
  failed_when: false
  when:
    - ansible_facts.packages | select('match', '^xorg-x11-server-') | list | length > 0
    - is_x11_required == "no"
    - rhel8_cis_rule_2_1_5
  tags:
    - level1
    - scored
    - xwindows
    - patch
    - rule_2.1.5


### Verificación Paquete avahi y avahi-autopd
# Tarea 2.1.6 - Solicitar al usuario si avahi es requerido
- name: Solicitar al usuario si avahi es requerido
  pause:
    prompt: "¿El paquete avahi está instalado? Avahi es un sistema de descubrimiento de servicios en la red. ¿Este sistema utiliza avahi? (yes/no)"
  register: is_avahi_required
  when: "'avahi' in ansible_facts.packages or 'avahi-autopd' in ansible_facts.packages"
# Tarea 2.1.6 Asegurar Avahi Server no esté instalado (Automático)
- name: SCORED | 2.1.6 | PATCH | Ensure Avahi Server is not enabled
  service:
    name:
        - avahi-autoipd
        - avahi
    state: stopped
    enabled: no
  when:
    - "'avahi' in ansible_facts.packages or 'avahi-autopd' in ansible_facts.packages"
    - is_avahi_required == "no"
    - rhel8_cis_rule_2_1_6
  tags:
    - level1
    - scored
    - avahi
    - services
    - patch
    - rule_2.1.6


### Verificación Paquete CUPS
# Tarea 2.1.7 - Solicitar al usuario si el sistema es un servidor CUPS
- name: Solicitar al usuario si el sistema es un servidor CUPS
  pause:
    prompt: "¿El paquete CUPS está instalado? CUPS es un sistema de impresión en red. ¿Es este sistema un servidor CUPS? (yes/no)"
  register: is_cups_server
  when: "'cups' in ansible_facts.packages"
# Tarea 2.1.7 - Asegurar que el paquete CUPS no está instalado
- name: SCORED | 2.1.7 | PATCH | Ensure CUPS is not installed
  package:
    name: cups
    state: absent
  when:
    - "'cups' in ansible_facts.packages"
    - is_cups_server == "no"
    - rhel8_cis_rule_2_1_7
  tags:
    - level1
    - scored
    - cups
    - services
    - patch
    - rule_2.1.7

## Verificación Paquete DHCP
# Tarea 2.1.8 - Solicitar al usuario si el sistema es un servidor DHCP
- name: Solicitar al usuario si el sistema es un servidor DHCP
  pause:
    prompt: "¿El paquete DHCPD está instalado? DHCP proporciona configuración automática de direcciones IP a dispositivos en la red. ¿Es este sistema un servidor DHCP? (yes/no)"
  register: is_dhcp_server
  when: "'dhcpd' in ansible_facts.packages"
# Tarea 2.1.8 - Asegurar que el paquete DHCP Server no está instalado
- name: SCORED | 2.1.8 | PATCH | Ensure DHCP Server is not installed
  package:
    name: dhcpd
    state: absent
  when:
    - "'dhcpd' in ansible_facts.packages"
    - is_dhcp_server == "no"
    - rhel8_cis_rule_2_1.8
  tags:
    - level1
    - scored
    - dhcp
    - services
    - patch
    - rule_2.1.8

## Verificación Paquete LDAP SERVER
# Tarea 2.1.9 - Solicitar al usuario si el sistema es un servidor LDAP
- name: Solicitar al usuario si el sistema es un servidor LDAP 
  pause:
    prompt: "¿El paquete openldap-servers está instalado? Un servidor LDAP proporciona un servicio de directorio para gestionar y acceder a información de usuarios y recursos. ¿Es este sistema un servidor LDAP? (yes/no)"
  register: is_ldap_server
  when: "'openldap-servers' in ansible_facts.packages"
# Tarea 2.1.9 - Asegurar que el paquete LDAP Server no está instalado
- name: SCORED | 2.1.9 | PATCH | Ensure LDAP Server is not installed
  package:
    name: openldap-servers
    state: absent
  when:
    - "'openldap-servers' in ansible_facts.packages"
    - is_ldap_server == "no"
    - rhel8_cis_rule_2_1_9
  tags:
    - level1
    - scored
    - ldap
    - services
    - patch
    - rule_2.1.9

## Verificación Paquete NFS
# Tarea 2.1.10 - Solicitar al usuario si el sistema utiliza NFS
- name: Solicitar al usuario si el sistema utiliza NFS
  pause:
    prompt: "¿El paquete nfs-utils o nfs-kernel-server están instalados? NFS permite compartir archivos entre sistemas en una red. ¿Este sistema utiliza NFS? (yes/no)"
  register: nfs_service_needed
  when: "'nfs-utils' in ansible_facts.packages or 'nfs-kernel-server' in ansible_facts.packages"
# Tarea 2.1.10 - Asegurar que el paquete NFS no está instalado
- name: SCORED | 2.1.10 | PATCH | Ensure NFS is not installed
  package:
    name: 
      - nfs-utils
      - nfs-kernel-server
    state: absent
  when:
    - "'nfs-utils' in ansible_facts.packages or 'nfs-kernel-server' in ansible_facts.packages"
    - nfs_service_needed == "no"
    - rhel8_cis_rule_2_1.10
  tags:
    - level1
    - scored
    - nfs
    - rpc
    - services
    - patch
    - rule_2.1.10

## Verificación Paquete DNS
# Tarea 2.1.11 - Solicitar al usuario si el sistema es un servidor DNS
- name: Solicitar al usuario si el sistema es un servidor DNS
  pause:
    prompt: "¿El paquete bind o bind-chroot están instalados? Un servidor DNS traduce nombres de dominio en direcciones IP, facilitando la navegación por la web y el acceso a recursos. ¿Es este sistema un servidor DNS? (yes/no)"
  register: is_dns_server
  when: "'bind' in ansible_facts.packages or 'bind-chroot' in ansible_facts.packages"
# Tarea 2.1.11 - Asegurar que los paquetes del servidor DNS no están instalados
- name: SCORED | 2.1.11 | PATCH | Ensure DNS Server packages are not installed
  package:
    name:
      - bind
      - bind-chroot
    state: absent
  when:
    - "'bind' in ansible_facts.packages or 'bind-chroot' in ansible_facts.packages"
    - is_dns_server == "no"
    - rhel8_cis_rule_2_1.11
  tags:
    - level1
    - scored
    - bind
    - patch
    - rule_2.1.11

## Verificación Paquete FTP
# Tarea 2.1.12 y 2.1.13 - Solicitar al usuario si el sistema es un servidor FTP
- name: Solicitar al usuario si el sistema es un servidor FTP
  pause:
    prompt: "¿El paquete vsftpd está instalado? Un servidor FTP permite la transferencia de archivos entre sistemas a través de la red, facilitando la carga y descarga de datos. ¿Es este sistema un servidor FTP? (yes/no)"
  register: is_ftp_server
  when: "'vsftpd' in ansible_facts.packages"
# Tarea 2.1.12 y 2.1.13 - Asegurar que los paquetes FTP y VSFTPD no están instalados
- name: "SCORED | 2.1.12 | PATCH | Ensure FTP  packages are not installed\n SCORED\
    \ | 2.1.13 | PATCH | Ensure VSFTPD  packages are not installed"
  package:
    name: vsftpd
    state: absent
  when:
    - "'vsftpd' in ansible_facts.packages"
    - is_ftp_server == "no"
    - rhel8_cis_rule_2_1.12
    - rhel8_cis_rule_2_1.13
  tags:
    - level1
    - scored
    - ftp
    - patch
    - rule_2.1.12
    - rule_2.1.13

## Verificación Paquete TFTP
# Tarea 2.1.14 - Solicitar al usuario si el sistema es un servidor TFTP
- name: Solicitar al usuario si el sistema es un servidor TFTP
  pause:
    prompt: "¿El paquete tftp-server está instalado? Un servidor TFTP permite la transferencia de archivos de forma simple y sin autenticación, ideal para tareas como la carga de archivos de configuración en dispositivos de red. ¿Es este sistema un servidor TFTP? (yes/no)"
  register: is_tftp_server
  when: "'tftp-server' in ansible_facts.packages"
# Tarea 2.1.14 - Asegurar que los paquetes TFTP no están instalados
- name: SCORED | 2.1.14 | PATCH | Ensure TFTP packages are not installed
  package:
    name: tftp-server
    state: absent
  when:
    - "'tftp-server' in ansible_facts.packages"
    - is_tftp_server == "no"
    - rhel8_cis_rule_2_1.14
  tags:
    - level1
    - scored
    - tftp
    - patch
    - rule_2.1.14

## Verificación Paquete HTTP
# Tarea 2.1.15 - Solicitar al usuario si el sistema es un servidor HTTP
- name: Solicitar al usuario si el sistema es un servidor HTTP
  pause:
    prompt: "¿El paquete httpd está instalado? Un servidor HTTP gestiona solicitudes de recursos web, permitiendo la entrega de páginas y aplicaciones a través de Internet. ¿Es este sistema un servidor HTTP? (yes/no)"
  register: is_http_server
  when: "'httpd' in ansible_facts.packages"
# Tarea 2.1.15 - Asegurar que el paquete del servidor HTTP no está instalado
- name: SCORED | 2.1.15 | PATCH | Ensure HTTP Server package is not installed
  package:
    name: httpd
    state: absent
  when:
    - "'httpd' in ansible_facts.packages"
    - is_http_server == "no"
    - rhel8_cis_rule_2_1.15
  tags:
    - level1
    - scored
    - http
    - patch
    - rule_2.1.15

## Verificación Paquete IMAP - POP3
# Tarea 2.1.16 - Solicitar al usuario si el sistema es un servidor IMAP o POP3
- name: Solicitar al usuario si el sistema es un servidor IMAP o POP3
  pause:
    prompt: "¿El paquete dovecot está instalado? Dovecot es un servidor de correo que permite acceder a correos a través de IMAP y POP3. ¿Es este sistema un servidor IMAP o POP3? (yes/no)"
  register: is_imap_pop3_server
  when: "'dovecot' in ansible_facts.packages"
# Tarea 2.1.16 - Asegurar que los paquetes del servidor IMAP y POP3 no están instalados
- name: SCORED | 2.1.16 | PATCH | Ensure IMAP and POP3 Server packages are not installed
  package:
    name: dovecot
    state: absent
  when:
    - "'dovecot' in ansible_facts.packages"
    - is_imap_pop3_server == "no"
    - rhel8_cis_rule_2_1.16
  tags:
    - level1
    - scored
    - dovecot
    - patch
    - rule_2.1.16

## Verificación Paquete SAMBA
# Tarea 2.1.17 - Solicitar al usuario si el sistema utiliza Samba
- name: Solicitar al usuario si el sistema utiliza Samba
  pause:
    prompt: "¿El paquete samba está instalado? Samba permite compartir archivos e impresoras con sistemas Windows. ¿Este sistema utiliza Samba? (yes/no)"
  register: samba_needed
  when: "'samba' in ansible_facts.packages"
# Tarea 2.1.17 - Asegurar que el paquete Samba no está instalado
- name: SCORED | 2.1.17 | PATCH | Ensure Samba package is not installed
  package:
    name: samba
    state: absent
  when:
    - "'samba' in ansible_facts.packages"
    - samba_needed == "no"
    - rhel8_cis_rule_2_1_17
  tags:
    - level1
    - scored
    - samba
    - patch
    - rule_2_1_17

## Verificación Paquete HTTP Proxy
# Tarea 2.1.18 - Solicitar al usuario si el sistema es un servidor HTTP Proxy
- name: Solicitar al usuario si el sistema es un servidor HTTP Proxy
  pause:
    prompt: "¿El paquete squid está instalado? Squid es un servidor de proxy HTTP para mejorar el rendimiento y la privacidad. ¿Es este sistema un servidor HTTP Proxy? (yes/no)"
  register: is_http_proxy_server
  when: "'squid' in ansible_facts.packages"
# Tarea 2.1.18 - Asegurar que el paquete del servidor HTTP Proxy no está instalado
- name: SCORED | 2.1.18 | PATCH | Ensure HTTP Proxy Server package is not installed
  package:
    name: squid
    state: absent
  when:
    - "'squid' in ansible_facts.packages"
    - is_http_proxy_server == "no"
    - rhel8_cis_rule_2_1.18
  tags:
    - level1
    - scored
    - patch
    - squid
    - rule_2.1.18

## Verificación Paquete SNMP
# Tarea 2.1.19 - Solicitar al usuario si el sistema utiliza SNMP
- name: Solicitar al usuario si el sistema utiliza SNMP
  pause:
    prompt: "¿El paquete net-snmp está instalado? SNMP (Simple Network Management Protocol) se usa para gestionar y monitorizar dispositivos en redes. ¿Este sistema utiliza SNMP? (yes/no)"
  register: is_snmp_enabled
  when: "'net-snmp' in ansible_facts.packages"
# Tarea 2.1.19 - Asegurar que el servicio SNMP está deshabilitado
- name: SCORED | 2.1.19 | PATCH | Ensure SNMP service is disabled
  service:
    name: snmpd
    state: stopped
    enabled: no
  when:
    - "'net-snmp' in ansible_facts.packages"
    - is_snmp_enabled == "no"
    - rhel8_cis_rule_2_1.19
  tags:
    - level1
    - scored
    - snmp
    - patch
    - rule_2.1.19

## Verificación configuracion mail transfer agent en modo local-only
# Tarea 2.1.21 - Solicitar al usuario si el sistema es un servidor Mail
- name: Solicitar al usuario si el sistema es un servidor Mail
  pause:
    prompt: "¿El paquete postfix está instalado? Postfix es un agente de transferencia de correo (MTA) usado para enviar y recibir correos. ¿Es este sistema un servidor Mail? (yes/no)"
  register: is_mail_server
  when: "'postfix' in ansible_facts.packages"
# 2.1.20 Asegurar que el agente de mail transfer está configurado para modo  local-only (Automático)
- name: "2.1.20 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify: Restart postfix
  when:
      - "'postfix' in ansible_facts.packages"
      - is_mail_server == "no"
      - rhel8_cis_rule_2_1_20
  tags:
      - level1
      - patch
      - postfix
      - rule_2.1.20

## Verificación Paquete TELNET SERVER
# Tarea 2.1.21 - Solicitar al usuario si el sistema es un servidor Telnet
- name: Solicitar al usuario si el sistema es un servidor Telnet
  pause:
    prompt: "¿El paquete telnet-server está instalado? Un servidor Telnet permite el acceso remoto a dispositivos y servicios a través de una interfaz de línea de comandos, aunque utiliza un protocolo inseguro. ¿Es este sistema un servidor Telnet? (yes/no)"
  register: is_telnet_server
  when: "'telnet-server' in ansible_facts.packages"
# Tarea 2.1.21 - Asegurar que el paquete Telnet Server no está instalado
- name: SCORED | 2.1.21 | PATCH | Ensure Telnet Server package is not installed
  package:
    name: telnet-server
    state: absent
  when:
    - "'telnet-server' in ansible_facts.packages"
    - is_telnet_server == "no"
    - rhel8_cis_rule_2_1.21
  tags:
    - level1
    - scored
    - telnet
    - patch
    - rule_2.1.21

## Verificación Paquete RSYNC
# Tarea 2.1.22 - Solicitar al usuario si el sistema utiliza Rsync
- name: Solicitar al usuario si el sistema utiliza Rsync
  pause:
    prompt: "¿El paquete rsync está instalado? Rsync es una herramienta para la sincronización de archivos. ¿Este sistema utiliza Rsync? (yes/no)"
  register: rsync_needed
  when: "'rsync' in ansible_facts.packages"
# Tarea 2.1.22 - Asegurar que el paquete Rsync no está instalado
- name: SCORED | 2.1.22 | PATCH | Ensure Rsync package is not installed
  package:
    name: rsync
    state: absent
  when:
    - "'rsync' in ansible_facts.packages"
    - rsync_needed == "no"
    - rhel8_cis_rule_2_1.22
  tags:
    - level1
    - scored
    - rsync
    - patch
    - rule_2.1.22

## Verificación Paquete NIS SERVER (Network Information Service)
# Tarea 2.1.23 - Solicitar al usuario si el sistema es un servidor NIS
- name: Solicitar al usuario si el sistema es un servidor NIS
  pause:
    prompt: "¿El paquete ypserv está instalado? Un servidor NIS (Network Information Service) facilita la gestión centralizada de información sobre usuarios y grupos en una red, permitiendo que los sistemas obtengan esta información de manera eficiente. ¿Es este sistema un servidor NIS? (yes/no)"
  register: is_nis_server
  when: "'ypserv' in ansible_facts.packages"
# Tarea 2.1.23 - Asegurar que el paquete NIS Server no está instalado
- name: SCORED | 2.1.23 | PATCH | Ensure NIS Server package is not installed
  package:
    name: ypserv
    state: absent
  when:
    - "'ypserv' in ansible_facts.packages"
    - is_nis_server == "no"
    - rhel8_cis_rule_2_1.23
  tags:
    - level1
    - scored
    - nis
    - patch
    - rule_2.1.23
