---
# Tarea 5.2.1 - Asegurar sudo está instalado (Automático)
- name: "5.2.1 | PATCH | Ensure sudo is installed"
  ansible.builtin.package:
    name: sudo
    state: present
  when: rhel8_cis_rule_5_2_1 and ansible_facts.packages['sudo'] is not defined
  changed_when: false
  tags:
    - level1
    - patch
    - sudo
    - rule_5_2_1


# Tarea 5.2.2 - Asegurar que comandos sudo usen pty (Automático)
## DESHABILITADO - Validar afectacion con ansible
- name: "5.2.2 | PATCH | Ensure sudo commands use pty"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "Defaults    use_pty"
    validate: '/usr/sbin/visudo -cf %s'
  when:
    - rhel8_cis_rule_5_2_2
  tags:
    - level1
    - patch
    - sudo
    - rule_5.2.2

# Tarea 5.2.3 - Asegurar que existan archivos de logs de sudo (Automático)
- name: "5.2.3 | PATCH | Ensure sudo log file exists"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults    logfile='
    line: 'Defaults    logfile="{{ rhel8_cis_sudolog_location }}"'
    validate: '/usr/sbin/visudo -cf %s'
  when:
    - rhel8_cis_rule_5_2_3
  tags:
    - level1
    - patch
    - sudo
    - rule_5.2.3

# Tarea 5.2.4 - Asegurar que se debe proveer contraseña para escalamiento de usuarios (Automático)
- name: "5.2.4 | PATCH | Ensure users must provide password for escalation"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '^([^#|{% if system_is_ec2 %}ec2-user{% endif %}].*)NOPASSWD(.*)'
    replace: '\1PASSWD\2'
    validate: '/usr/sbin/visudo -cf %s'
  loop: "{{ rhel8_cis_sudoers_files.stdout_lines }}"
  when:
    - rhel8_cis_rule_5_2_4
  tags:
    - level2
    - patch
    - sudo
    - rule_5.2.4

# Tarea 5.2.5 - Asegurar que la re-authentication para escalamiento de privilegios no esté globalmente deshabilitada (Automático)
- name: "5.2.5 | PATCH | Ensure re-authentication for privilege escalation is not disabled globally"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '^([^#].*)!authenticate(.*)'
    replace: '\1authenticate\2'
    validate: '/usr/sbin/visudo -cf %s'
  loop: "{{ rhel8_cis_sudoers_files.stdout_lines }}"
  when:
    - rhel8_cis_rule_5_2_5
  tags:
    - level1
    - patch
    - sudo
    - rule_5.2.5

# Tarea 5.2.6 - Asegurar que sudo authentication timeout está configurado correctamente (Automático)
- name: "5.2.6 | PATCH | Ensure sudo authentication timeout is configured correctly"
  block:
    - name: "5.2.6 | AUDIT | Ensure sudo authentication timeout is configured correctly | Get files with timeout set"
      ansible.builtin.shell: grep -is 'timestamp_timeout' /etc/sudoers /etc/sudoers.d/* | cut -d":" -f1 | uniq | sort
      changed_when: false
      failed_when: false
      register: rhel8_cis_5_2_6_timeout_files

    - name: "5.2.6 | PATCH | Ensure sudo authentication timeout is configured correctly | Set value if no results"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: 'Defaults timestamp_timeout='
        line: "Defaults timestamp_timeout={{ rhel8_cis_sudo_timestamp_timeout }}"
        validate: '/usr/sbin/visudo -cf %s'
      when: rhel8_cis_5_2_6_timeout_files.stdout | length == 0

    - name: "5.2.6 | PATCH | Ensure sudo authentication timeout is configured correctly | Set value if has results"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: 'timestamp_timeout=(\d+)'
        replace: "timestamp_timeout={{ rhel8_cis_sudo_timestamp_timeout }}"
        validate: '/usr/sbin/visudo -cf %s'
      loop: "{{ rhel8_cis_5_2_6_timeout_files.stdout_lines }}"
      when: rhel8_cis_5_2_6_timeout_files.stdout | length > 0
  when:
    - rhel8_cis_rule_5_2_6
  tags:
    - level1
    - patch
    - sudo
    - rule_5.2.6

# Tarea 5.2.7 - Asegurar que el acceso al comando SU está restringido (Automático)
## DESHABILITADO - esta restriccion de SU es bastante restrictiva y afectaria el acceso a root
- name: "5.2.7 | PATCH | Ensure access to the su command is restricted"
  block:
    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | Ensure sugroup exists"
      ansible.builtin.group:
        name: "{{ rhel8_cis_sugroup }}"
        state: present
      register: rhel8_cis_5_2_7_sugroup

    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | remove users from group"
      ansible.builtin.lineinfile:
        path: /etc/group
        regexp: '^{{ rhel8_cis_sugroup }}(:.:.*:).*$'
        line: '{{ rhel8_cis_sugroup }}\g<1>'
        backrefs: true

    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
      ansible.builtin.lineinfile:
        path: /etc/pam.d/su
        regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
        line: 'auth           required        pam_wheel.so use_uid group={{ rhel8_cis_sugroup }}'
  when:
    - rhel8_cis_rule_5_2_7
  tags:
    - level1
    - patch
    - sudo
    - rule_5.2.7


