---

# Tarea 5.2.8 - Asegurar que es usado el perfil personalizado de authselect (Manual)
- name: "5.2.8 | PATCH | Ensure custom authselect profile is used"
  block:
    - name: "5.2.8 | AUDIT | Ensure custom authselect profile is used | Gather profiles"
      ansible.builtin.command: authselect list
      register: rhel8_cis_5_2_8_current_profile
      failed_when: false
      changed_when: false
      check_mode: false

    - name: "5.2.8 | PATCH | Ensure custom authselect profile is used | Create custom profiles"
      ansible.builtin.command:
        cmd: >
          authselect create-profile {{ rhel8_cis_authselect['custom_profile_name'] }}
          -b {{ rhel8_cis_authselect['default_file_to_copy'] }}
      changed_when: false
      when:
        - rhel8_cis_authselect_custom_profile_create
        - "rhel8_cis_authselect.custom_profile_name not in rhel8_cis_5_2_8_current_profile.stdout"

    - name: "5.2.8 | PATCH | Ensure custom authselect profile is used | Force custom profile creates backup"
      ansible.builtin.command:
        cmd: >
          authselect select custom/{{ rhel8_cis_authselect['custom_profile_name'] }}
          --force --backup=rhel8cis_5_2_8_{{ ansible_date_time.epoch }}
      register: authselect_5_4_1_select
      changed_when: false
      when:
        - rhel8_cis_authselect_custom_profile_create
        - "rhel8_cis_authselect.custom_profile_name not in rhel8_cis_5_2_8_current_profile.stdout"
  when:
    - rhel8_cis_rule_5_2_8
  tags:
    - level1
    - manual
    - patch
    - authselect
    - rule_5.2.8


# Tarea 5.2.9 - Asegurar que el authselect incluye with-faillock (Automático)
- name: "5.2.7 | PATCH | Ensure access to the su command is restricted"
  block:
    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | Ensure nosugroup exists"
      ansible.builtin.group:
        name: "{{ rhel8_cis_sugroup }}"
        state: present

    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | Clean nosugroup membership"
      ansible.builtin.lineinfile:
        path: /etc/group
        regexp: '^{{ rhel8_cis_sugroup }}(:.:.*:).*$'
        line: '{{ rhel8_cis_sugroup }}\g<1>'
        backrefs: true

    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | Add INFRA_TI users to nosugroup"
      ansible.builtin.user:
        name: "{{ item }}"
        groups: "{{ rhel8_cis_sugroup }}"
        append: true
      with_items: "{{ rhel8_cis_users_infra }}"

    - name: "5.2.7 | PATCH | Ensure access to the su command is restricted | Configure pam_wheel for nosugroup"
      ansible.builtin.lineinfile:
        path: /etc/pam.d/su
        regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
        line: 'auth           required        pam_wheel.so use_uid group={{ rhel8_cis_sugroup }}'

  when:
    - rhel8_cis_rule_5_2_7
  tags:
    - level1
    - patch
    - sudo
    - rule_5.2.7

