---

# 5.1.1 Asegurar cron daemon está habilitado y ejecutándose (Automático)
- name: SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled
  ansible.builtin.service:
    name: crond
    enabled: true
  when:
    - rhel8_cis_rule_5_1_1
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.1

# Tarea 5.1.2 - Asegurar que los permisos en /etc/crontab estén configurados
- name: SCORED | 5.1.2 | PATCH | Ensure permissions on /etc/crontab are configured
  ansible.builtin.file:
    dest: /etc/crontab
    owner: root
    group: root
    mode: "0600"
  when:
    - rhel8_cis_rule_5_1_2
  tags:
    - level1
    - level2
    - patch
    - crontab
    - rule_5.1.2

# Tarea 5.1.3 - Asegurar que los permisos en /etc/cron.hourly estén configurados
- name: SCORED | 5.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured
  ansible.builtin.file:
    dest: /etc/cron.hourly
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - rhel8_cis_rule_5_1_3
  tags:
    - level1
    - level2
    - patch
    - crontab
    - rule_5.1.3

# Tarea 5.1.4 - Asegurar que los permisos en /etc/cron.daily estén configurados
- name: SCORED | 5.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured
  ansible.builtin.file:
    dest: /etc/cron.daily
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - rhel8_cis_rule_5_1_4
  tags:
    - level1
    - level2
    - patch
    - crontab
    - rule_5.1.4

# Tarea 5.1.5 - Asegurar que los permisos en /etc/cron.weekly estén configurados
- name: SCORED | 5.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured
  ansible.builtin.file:
    dest: /etc/cron.weekly
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - rhel8_cis_rule_5_1_5
  tags:
    - level1
    - level2
    - patch
    - crontab
    - rule_5.1.5

# Tarea 5.1.6 - Asegurar que los permisos en /etc/cron.monthly estén configurados
- name: SCORED | 5.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured
  ansible.builtin.file:
    dest: /etc/cron.monthly
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - rhel8_cis_rule_5_1_6
  tags:
    - level1
    - level2
    - patch
    - crontab
    - rule_5.1.6

# Tarea 5.1.7 - Asegurar que los permisos en /etc/cron.d estén configurados
- name: SCORED | 5.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured
  ansible.builtin.file:
    dest: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - rhel8_cis_rule_5_1_7
  tags:
    - level1
    - level2
    - patch
    - crontab
    - rule_5.1.7

# Tarea 5.1.8 - Asegurar que cron esté restringido solo a usuarios autorizados (Automático)
### IMPORTANTE UNICAMENTE LOS USUARIOS QUE ESTAN EN /etc/cron.allow TIENEN PERMISOS PARA PROGRAMAR CRON
- name: "5.1.8 | PATCH | Ensure cron is restricted to authorized users"
  block:
    - name: "5.1.8 | PATCH | Remove cron.deny"
      ansible.builtin.file:
        path: /etc/cron.deny
        state: absent

    - name: "5.1.8 | PATCH | Check if cron.allow exists"
      ansible.builtin.stat:
        path: "/etc/cron.allow"
      register: cron_allow_state

    - name: "5.1.8 | PATCH | Ensure cron.allow exists"
      ansible.builtin.file:
        path: /etc/cron.allow
        state: touch
        owner: root
        group: root
        mode: "0600"
      when: not cron_allow_state.stat.exists

    - name: "5.1.8 | PATCH | Ensure cron.allow is restricted to authorized users"
      ansible.builtin.file:
        path: /etc/cron.allow
        owner: root
        group: root
        mode: "0600"

    - name: "5.1.8 | PATCH | Add authorized users to cron.allow"
      ansible.builtin.lineinfile:
        path: /etc/cron.allow
        line: "{{ item }}"
        state: present
      loop: "{{ authorized_cron_users | default([]) }}"
      when: authorized_cron_users is defined and authorized_cron_users | length > 0
  when:
    - rhel8_cis_rule_5_1_8 | default(false)
  tags:
    - level1
    - patch
    - cron
    - rule_5.1.8



# Tarea 5.1.9 - Asegurar que at esté restringido solo a usuarios autorizados (Automático)
### IMPORTANTE UNICAMENTE LOS USUARIOS QUE ESTAN EN /etc/at.allow TIENEN PERMISOS PARA PROGRAMAR AT
- name: "5.1.9 | PATCH | Ensure at is restricted to authorized users"
  block:
    - name: "5.1.9 | PATCH | Ensure at is restricted to authorized users | Remove at.deny"
      ansible.builtin.file:
        path: /etc/at.deny
        state: absent

    - name: "5.1.9 | PATCH | Ensure at is restricted to authorized users | Check if at.allow exists"
      ansible.builtin.stat:
        path: "/etc/at.allow"
      register: rhel8_cis_5_1_9_at_allow_state

    - name: "5.1.9 | PATCH | Ensure at is restricted to authorized users | Ensure at.allow is restricted to authorized users"
      ansible.builtin.file:
        path: /etc/at.allow
        state: '{{ "file" if rhel8_cis_5_1_9_at_allow_state.stat.exists else "touch" }}'
        owner: root
        group: root
        mode: "0600"

    - name: "5.1.9 | PATCH | Ensure at is restricted to authorized users | Add authorized users to at.allow"
      ansible.builtin.lineinfile:
        path: /etc/at.allow
        line: "{{ item }}"
        state: present
      loop: "{{ authorized_at_users }}"
  when:
    - rhel8_cis_rule_5_1_9
  tags:
    - level1
    - patch
    - at
    - rule_5.1.9


