---
# TAREA PRELIMINAR: Ejecuta las tareas preliminares necesarias
- name: "PRELIM | Run preliminary tasks"
  ansible.builtin.import_tasks:
    file: prelim.yml
  become: true
  tags:
    - prelim_tasks
    - always
    - rhel8cis_section5

# SECCIÓN 5.1.1-9: Configuración de trabajos programados basados en tiempo
- name: "SECTION | 5.1.1-9 | Set up time-based scheduled jobs"
  ansible.builtin.import_tasks:
    file: cis5.1-Scheduled_Jobs.yml   
  tags:
    - rhel8cis_section5
    - Scheduled_Jobs



