---

# Prelim requerido para la tarea 5.2.4 y 5.2.5 | Encuentra todos los archivos sudoers
- name: "PRELIM | Find all sudoers files."
  ansible.builtin.shell: "find /etc/sudoers /etc/sudoers.d/ -type f ! -name '*~' ! -name '*.*'"
  changed_when: false
  failed_when: false
  check_mode: false
  register: rhel8_cis_sudoers_files


# Prelim requerido para la tarea 5.3.2 | Buscar archivos de claves privadas del host SSH
- name: PRELIM | Ensure permissions on SSH private host key files are configured - find
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: ssh_host_*_key
  register: ssh_host_keys


# Prelim requerido para la tarea 5.3.3 | Buscar archivos de claves públicas del host SSH
- name: PRELIM | Ensure permissions on SSH public host key files are configured - find
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: ssh_host_*_key.pub
  register: ssh_host_keys

 
# Prelim requerido para la tarea 5.5.1 - identificar usuarios interactivos en el sistema
- name: "PRELIM | AUDIT | Identify interactive users"
  ansible.builtin.command: >
    awk -F: -v excluded="{{ excluded_users | join('|') }}"
          -v min_uid="{{ min_int_uid }}"
          '($3 >= min_uid && $1 !~ excluded && $7 !~ /(nologin|false|null)/) { print $1 }' /etc/passwd
  changed_when: false
  register: discovered_interactive_usernames
  tags:
    - always

  # Prelim requerido para la tarea 5.5.6 | Obtener lista de usuarios del sistema 
- name: "Generate rhel8_cis_passwd list"
  ansible.builtin.shell: |
    getent passwd | awk -F: '{print "{\"id\": \""$1"\", \"uid\": "$3", \"shell\": \""$7"\"}"}'
  register: passwd_data
  changed_when: false
  check_mode: false

- name: "Set rhel8_cis_passwd variable"
  ansible.builtin.set_fact:
    rhel8_cis_passwd: "{{ passwd_data.stdout_lines | map('from_json') | list }}"


# Prelim requerido para la tarea 5.5.7 | Verificar GID del usuario root 
- name: PRELIM | Verify GID of root user
  ansible.builtin.command:
    cmd: "id -g root"
  register: root_gid_check
  check_mode: false  # Desactiva check mode solo para esta tarea
  become: true
  changed_when: false


