--- 
# Tarea 3.3.1 - Asegurar que source routed packets no son aceptados (Automático)
- name: SCORED | 3.3.1 | PATCH | Ensure source routed packets are not accepted
  block:
    - name: SCORED | 3.3.1 | PATCH | Ensure source routed IPv4 packets are not accepted
      ansible.builtin.sysctl:
        name: '{{ item }}'
        value: '0'
        sysctl_set: true
        state: present
        reload: true
        sysctl_file: /etc/sysctl.d/cis.conf
      loop:
        - net.ipv4.conf.all.accept_source_route
        - net.ipv4.conf.default.accept_source_route
      notify:
        - sysctl flush ipv4 route table

    - name: SCORED | 3.3.1 | PATCH | Ensure source routed IPv6 packets are not accepted
      ansible.builtin.sysctl:
        name: '{{ item }}'
        value: '0'
        sysctl_set: true
        state: present
        reload: true
        sysctl_file: /etc/sysctl.d/cis.conf
      loop:
        - net.ipv6.conf.all.accept_source_route
        - net.ipv6.conf.default.accept_source_route
      when:
        - rhel8_cis_ipv6_required
      notify:
        - sysctl flush ipv6 route table
  when:
    - rhel8_cis_rule_3_3_1
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.1

# Tarea 3.3.2 - Asegurar que ICMP redirects no son aceptados (Automático)
- name: SCORED | 3.3.2 | PATCH | Ensure ICMP redirects are not accepted
  block:
    - name: SCORED | 3.3.2 | PATCH | Ensure ICMP redirects are not accepted
      ansible.builtin.sysctl:
        name: '{{ item }}'
        value: '0'
        sysctl_set: true
        state: present
        reload: true
        sysctl_file: /etc/sysctl.d/cis.conf
      loop:
        - net.ipv4.conf.all.accept_redirects
        - net.ipv4.conf.default.accept_redirects
      notify:
        - sysctl flush ipv4 route table

    - name: SCORED | 3.3.2 | PATCH | Ensure ICMPv6 redirects are not accepted
      ansible.builtin.sysctl:
        name: '{{ item }}'
        value: '0'
        sysctl_set: true
        state: present
        reload: true
        sysctl_file: /etc/sysctl.d/cis.conf
      loop:
        - net.ipv6.conf.all.accept_redirects
        - net.ipv6.conf.default.accept_redirects
      when:
        - rhel8_cis_ipv6_required
      notify:
        - sysctl flush ipv6 route table
  when:
    - rhel8_cis_rule_3_3_2
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.2

# Tarea 3.3.3 - Asegurar que secure ICMP redirects no son aceptados (Automático)
- name: SCORED | 3.3.3 | PATCH | Ensure secure ICMP redirects are not accepted
  ansible.builtin.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  loop:
    - {name: net.ipv4.conf.all.secure_redirects, value: 0}
    - {name: net.ipv4.conf.default.secure_redirects, value: 0}
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8_cis_rule_3_3_3
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.3

# Tarea 3.3.4 - Asegurar que suspicious packets son registrados (Automático)
- name: SCORED | 3.3.4 | PATCH | Ensure suspicious packets are logged
  ansible.builtin.sysctl:
    name: '{{ item }}'
    value: '1'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  loop:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8_cis_rule_3_3_4
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.4

# Tarea 3.3.5 - Asegurar que broadcast ICMP requests son ignoradas (Automático)
- name: SCORED | 3.3.5 | PATCH | Ensure broadcast ICMP requests are ignored
  ansible.builtin.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8_cis_rule_3_3_5
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.5

# Tarea 3.3.6 - Asegurar bogus ICMP responses son ignoradas (Automático)
- name: SCORED | 3.3.6 | PATCH | Ensure bogus ICMP responses are ignored
  ansible.builtin.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: '1'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8_cis_rule_3_3_6
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.6

# Tarea 3.3.7 - Asegurar Reverse Path Filtering está habilitado (Automático)
- name: SCORED | 3.3.7 | PATCH | Ensure Reverse Path Filtering is enabled
  ansible.builtin.sysctl:
    name: '{{ item }}'
    value: '1'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  loop:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8_cis_rule_3_3_7
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.7

# Tarea 3.3.8 - Asegurar TCP SYN Cookies está habilitado (Automático)
- name: SCORED | 3.3.8 | PATCH | Ensure TCP SYN Cookies is enabled
  ansible.builtin.sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  notify:
    - sysctl flush ipv4 route table
  when:
    - rhel8_cis_rule_3_3_8
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.8

# Tarea 3.3.9 - Asegurar  que los anuncios de IPv6 router no son aceptados (Automático)
- name: SCORED | 3.3.9 | PATCH | Ensure IPv6 router advertisements are not accepted
  ansible.builtin.sysctl:
    name: '{{ item }}'
    value: '0'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/cis.conf
  loop:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
  notify:
    - sysctl flush ipv6 route table
  when:
    - rhel8_cis_ipv6_required
    - rhel8_cis_rule_3_3_9
  tags:
    - level1
    - sysctl
    - patch
    - rule_3.3.9

