---
# Tarea 1.1.5 - Asegurar que exista una partición separada para /tmp
- name: SCORED | 1.1.5 | PATCH | Ensure separate partition exists for /tmp
  ansible.builtin.debug: msg={{ item.mount }}
  loop: "{{ ansible_mounts | selectattr('mount', 'equalto', '/tmp') | list }}"
  changed_when: false
  when:
    - rhel8_cis_rule_1_1_7
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.7
    - skip_ansible_lint

- name: Depuración avanzada del módulo mount
  ansible.builtin.debug:
    msg:
      - "src: {{ rhel8_cis_tmp['source'] }}"
      - "fstype: {{ rhel8_cis_tmp['fstype'] }}"
      - "opts: {{ rhel8_cis_tmp['opts'] }}"

# Tarea 1.1.6-8 - Asegurar que las opciones nodev, nosuid y noexec se apliquen en la partición /tmp
- name: "SCORED | 1.1.6  | PATCH | Ensure nodev option set on /tmp partition\n\
    \ SCORED | 1.1.7  | PATCH | Ensure nosuid option set on /tmp partition\n SCORED\
    \ | 1.1.8 | PATCH | Ensure noexec option set on /tmp partition"
  ansible.builtin.mount:
    name: /tmp
    src: "{{ rhel8_cis_tmp['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_tmp['fstype'] }}"
    opts: "{{ rhel8_cis_tmp['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_rule_1_1_6
    - rhel8_cis_rule_1_1_7
    - rhel8_cis_rule_1_1_8
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.6_tmp
    - rule_1.1.7_tmp
    - rule_1.1.8_tmp

# Tarea 1.1.9 - Asegurar que /dev/shm esté en una partición separada (Automático)
- name: NOTSCORED | 1.1.9 | PATCH | Ensure that /dev/shm is in a separate partition (Automatic)
  ansible.builtin.debug:
    msg: --> Not relevant
  changed_when: false   
  when:
    - rhel8_cis_rule_1_1_9
  tags:
    - level1
    - notscored
    - patch
    - rule_1.1.9 

# Tarea 1.1.10-12 - Asegurar que las opciones nodev, nosuid y noexec se apliquen en la partición /dev/shm
# Validar si persiste tras el reinicio; si no, validar con /etc/systemd/tmp.mount.d
- name: "SCORED | 1.1.10  | PATCH | Ensure nodev option set on /dev/shm partition\n\
    \ SCORED | 1.1.11  | PATCH | Ensure nosuid option set on /dev/shm partition\n SCORED\
    \ | 1.1.12 | PATCH | Ensure noexec option set on /dev/shm partition"
  ansible.builtin.mount:
    name: /dev/shm
    src: "{{ rhel8_cis_shm['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_shm['fstype'] }}"
    opts: "{{ rhel8_cis_shm['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_shm['enabled'] == 'true'
    - rhel8_cis_rule_1_1_10
    - rhel8_cis_rule_1_1_11
    - rhel8_cis_rule_1_1_12
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.10_shm
    - rule_1.1.11_shm
    - rule_1.1.12_shm

# Tarea 1.1.13 - Asegurar que exista una partición separada para /var
- name: SCORED | 1.1.13 | PATCH | Ensure separate partition exists for /var
  ansible.builtin.debug: msg={{ item.mount }}
  loop: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var') | list }}"
  changed_when: false
  when:
    - rhel8_cis_rule_1_1_13
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.13
    - skip_ansible_lint

# Tarea 1.1.14-16 - Asegurar que las opciones nodev, nosuid y noexec se apliquen en la partición /var
- name: "SCORED | 1.1.14  | PATCH | Ensure nodev option set on /var partition\n\
    \ SCORED | 1.1.15  | PATCH | Ensure nosuid option set on /var partition\n SCORED\
    \ | 1.1.16 | PATCH | Ensure noexec option set on /var partition"
  ansible.builtin.mount:
    name: /var
    src: "{{ rhel8_cis_var['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_var['fstype'] }}"
    opts: "{{ rhel8_cis_var['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_var['enabled'] == 'true'
    - rhel8_cis_rule_1_1_14
    - rhel8_cis_rule_1_1_15
    - rhel8_cis_rule_1_1_16
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.14_tmp
    - rule_1.1.15_tmp
    - rule_1.1.16_tmp

# Tarea 1.1.17 - Asegurar que exista una partición separada para /var/tmp
- name: SCORED | 1.1.17 | PATCH | Ensure separate partition exists for /var/tmp
  ansible.builtin.debug: msg={{ item.mount }}
  loop: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var/tmp') | list }}"
  changed_when: false
  when:
    - rhel8_cis_rule_1_1_17
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.17
    - skip_ansible_lint

# Tarea 1.1.18-20 - Asegurar que las opciones nodev, nosuid y noexec se apliquen en la partición /var/tmp
- name: "SCORED | 1.1.18  | PATCH | Ensure nodev option set on /var/tmp partition\n\
    \ SCORED | 1.1.19  | PATCH | Ensure nosuid option set on /var/tmp partition\n SCORED\
    \ | 1.1.20 | PATCH | Ensure noexec option set on /var/tmp partition"
  ansible.builtin.mount:
    name: /var/tmp
    src: "{{ rhel8_cis_var_tmp['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_var_tmp['fstype'] }}"
    opts: "{{ rhel8_cis_var_tmp['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_var_tmp['enabled'] == 'true'
    - rhel8_cis_rule_1_1_18
    - rhel8_cis_rule_1_1_19
    - rhel8_cis_rule_1_1_20
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.18_tmp
    - rule_1.1.19_tmp
    - rule_1.1.20_tmp

# Tarea 1.1.21 - Asegurar que exista una partición separada para /var/log
- name: SCORED | 1.1.21 | PATCH | Ensure separate partition exists for /var/log
  ansible.builtin.debug: msg={{ item.mount }}
  loop: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list }}"
  changed_when: false
  when:
    - rhel8_cis_rule_1_1_21
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.21
    - skip_ansible_lint

# Tarea 1.1.22-24 - Asegurar que las opciones nodev, nosuid y noexec se apliquen en la partición /var/log
- name: "SCORED | 1.1.22  | PATCH | Ensure nodev option set on /var/log partition\n\
    \ SCORED | 1.1.23  | PATCH | Ensure nosuid option set on /var/log partition\n SCORED\
    \ | 1.1.24 | PATCH | Ensure noexec option set on /var/log partition"
  ansible.builtin.mount:
    name: /var/log
    src: "{{ rhel8_cis_var_log['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_var_log['fstype'] }}"
    opts: "{{ rhel8_cis_var_log['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_var_log['enabled'] == 'true'
    - rhel8_cis_rule_1_1_22
    - rhel8_cis_rule_1_1_23
    - rhel8_cis_rule_1_1_24
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.22_tmp
    - rule_1.1.23_tmp
    - rule_1.1.24_tmp

# Tarea 1.1.25 - Asegurar que exista una partición separada para /var/log/audit
- name: SCORED | 1.1.25 | PATCH | Ensure separate partition exists for /var/log/audit
  ansible.builtin.debug: msg={{ item.mount }}
  loop: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var/log/audit') | list }}"
  changed_when: false
  when:
    - rhel8_cis_rule_1_1_25
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.25
    - skip_ansible_lint

# Tarea 1.1.26-28 - Asegurar que las opciones nodev, nosuid y noexec se apliquen en la partición /var/log/audit
- name: "SCORED | 1.1.26  | PATCH | Ensure nodev option set on /var/log/audit partition\n\
    \ SCORED | 1.1.27  | PATCH | Ensure nosuid option set on /var/log/audit partition\n SCORED\
    \ | 1.1.28 | PATCH | Ensure noexec option set on /var/log/audit partition"
  ansible.builtin.mount:
    name: /var/log/audit
    src: "{{ rhel8_cis_var_log_audit['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_var_log_audit['fstype'] }}"
    opts: "{{ rhel8_cis_var_log_audit['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_var_log_audit['enabled'] == 'true'
    - rhel8_cis_rule_1_1_26
    - rhel8_cis_rule_1_1_27
    - rhel8_cis_rule_1_1_28
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.26_tmp
    - rule_1.1.27_tmp
    - rule_1.1.28_tmp

# Tarea 1.1.29 - Asegurar que exista una partición separada para /home
- name: SCORED | 1.1.29 | PATCH | Ensure separate partition exists for /home
  ansible.builtin.debug: msg={{ item.mount }}
  loop: "{{ ansible_mounts | selectattr('mount', 'equalto', '/home') | list }}"
  changed_when: false
  when:
    - rhel8_cis_rule_1_1_29
  tags:
    - level2
    - scored
    - patch
    - rule_1.1.29
    - skip_ansible_lint

# Tarea 1.1.32, 1.1.33, 1.1.34 - Asegurar que las opciones noexec, nodev y nosuid se apliquen en las particiones removibles
- name: NOTSCORED | 1.1.32 | 1.1.33 | 1.1.34 | PATCH | Ensure noexec, nodev, nosuid options set on removable media partitions
  ansible.builtin.debug:
    msg: --> Not relevant
  changed_when: false   
  when:
    - rhel8_cis_rule_1_1_32
    - rhel8_cis_rule_1_1_33
    - rhel8_cis_rule_1_1_34
  tags:
    - level1
    - notscored
    - patch
    - rule_1.1.32  
    - rule_1.1.33  
    - rule_1.1.34  

# Tarea 1.1.30,1.1.31,1.1.35,1.1.36 - Asegurar que las opciones nodev, nosuid, usrquota y grpquota se apliquen en la partición /home
- name: "SCORED | 1.1.30  | PATCH | Ensure nodev option set on /home partition\n\
    \ SCORED | 1.1.31  | PATCH | Ensure nosuid option set on /home partition\n SCORED\
    \ | 1.1.35 | PATCH | Ensure usrquota options set on /home partition\n SCORED\
    \ | 1.1.36 | PATCH | Ensure grpquota options set on /home partition"
  ansible.builtin.mount:
    name: /home
    src: "{{ rhel8_cis_home['source'] }}"
    state: mounted
    fstype: "{{ rhel8_cis_home['fstype'] }}"
    opts: "{{ rhel8_cis_home['opts'] }}"
    fstab: true
  when:
    - rhel8_cis_home['enabled'] == 'true'
    - rhel8_cis_rule_1_1_30
    - rhel8_cis_rule_1_1_31
    - rhel8_cis_rule_1_1_35
    - rhel8_cis_rule_1_1_36
  tags:
    - level1
    - scored
    - patch
    - rule_1.1.30_home
    - rule_1.1.31_home
    - rule_1.1.35_home
    - rule_1.1.36_home

# Tarea 1.1.37 - Asegurar que el sticky bit esté establecido sobre todos los directorios que son de escritura mundial (Automático)
- name: SCORED | 1.1.37 | PATCH | Ensure sticky bit is set on all world-writable directories
  ansible.builtin.shell: |
    set -o pipefail
    df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev \
      -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: false
  failed_when: false
  when:
    - rhel8_cis_rule_1_1_37
  tags:
    - level1
    - level2
    - patch
    - sticky_bit
    - rule_1.1.37


# Tarea 1.1.38 - Deshabilitar el Automounting
- name: Deshabilitar autofs si no hay NFS usándolo y las reglas de CIS lo permiten
  ansible.builtin.service:
    name: autofs
    enabled: false
    state: stopped
  when:
    - "'autofs' in ansible_facts.packages"
    - not autofs_config.stat.exists or autofs_nfs_check.stdout | length == 0
    - rhel8_cis_rule_1_1_38
  tags:
    - level1
    - level2
    - patch
    - autofs
    - rule_1.1.38

# Tarea 1.1.23 - Deshabilitar almacenamiento USB
- name: SCORED | 1.1.39 | PATCH | Disable USB Storage
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/cis.conf
    regexp: ^(#)?install usb-storage(\s|$)
    line: install usb-storage /bin/true
    mode: "0644"
    create: true
  when:
    - rhel8_cis_rule_1_1_39
  tags:
    - level1
    - level2
    - patch
    - rule_1.1.39
    - usb-storage

# Tarea 1.1.23 - Remover modulo de almacenamiento USB
- name: SCORED | 1.1.39 | PATCH | Remove USB Storage module
  ansible.builtin.modprobe:
    name: usb-storage
    state: absent
  when:
    - rhel8_cis_rule_1_1_39
    - ansible_virtualization_type != "docker"
  tags:
    - level1
    - level2
    - scored
    - patch
    - rule_1.1.39
    - usb-storage
