---
- name: Install Ansible collections
  hosts: localhost
  tasks:
    - name: Install collections from requirements.yml
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r /runner/project/roles/cis_security/collections/requirements.yml
      register: galaxy_output
      changed_when: "'Skipping' not in galaxy_output.stdout"

    - name: Show installation output
      ansible.builtin.debug:
        var: galaxy_output.stdout

    - name: List installed collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection list
      register: installed_collections
      changed_when: false

    - name: Show installed collections
      ansible.builtin.debug:
        var: installed_collections.stdout




