---
# handlers file for cis_security

# Tarea para reiniciar el servicio systemd-logind, que gestiona las sesiones de usuario y el manejo de dispositivos
- name: Reiniciar servicios PAM
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted

# Tarea para reiniciar el servicio sshd para aplicar cualquier cambio en su configuración
- name: Reiniciar sshd
  become: yes
  ansible.builtin.systemd:
    name: sshd
    state: restarted

# Tarea para limpiar las tablas de rutas IPv4 
- name: sysctl flush ipv4 route table
  become: yes
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    sysctl_set: yes
  when: ansible_virtualization_type != "docker"

# Tarea para limpiar las tablas de rutas IPv6
- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
    name: net.ipv6.route.flush
    value: 1
    sysctl_set: yes
  when: ansible_virtualization_type != "docker"

# Handler para verificar cambios y aplicar authselect solo si hubo modificaciones
- name: "Check authselect changes"
  block:
    - name: "Verify if authselect apply-changes is needed"
      ansible.builtin.command: authselect check
      register: authselect_check
      changed_when: "'No changes detected' not in authselect_check.stdout"

    - name: "Apply authselect changes"
      ansible.builtin.command: authselect apply-changes
      when: authselect_check.changed