---

## Crear Usuarios de Infraestructura con permisos de administrador y acceso SSH 
- name: Crear usuarios administradores
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ 'Colombia2025*' | password_hash('sha512') }}"
    groups: wheel,ssh_access
    shell: /bin/bash
    create_home: true
  loop:
    - aromero
    - csotomonte
    - jcastano


## Forzar que los usuarios administradores globales de Infraestructura cambien contrase침a en la siguiente session
- name: Forzar cambio de contrase침a en el pr칩ximo inicio de sesi칩n
  ansible.builtin.command: chage -d 0 "{{ item }}"
  loop:
    - aromero
    - csotomonte
    - jcastano
  changed_when: false 
